# cluster specific values
cluster:
  # specify cluster name
  name: aws-cluster

  # specify cluster labels
  labels: {}

  # specify cluster annotations
  annotations: {}

# specify cloud credential secret name, do not need to be provided if using custom driver
# cloudCredentialSecretName: "cattle-global-data:cc-kpg82"
# region: "eu-west-3"
# subnetId: "subnet-bc6c75d5"
# vpcId: "vpc-7456a51c"
# kubernetesVersion: "v1.24.10+rke2r1"
